server:
  port: 9999
#alibaba的druid数据库连接池配置
spring:
  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://localhost:3306/fsb?useUnicode=true&useSSL=false&characterEncoding=utf8   #生产读写分离
      username: cabin
      password: cabin8879576aA
      # 使用druid数据源
      filters: stat,wall,log4j #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      maxActive: 200
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      removeAbandoned: true
      removeAbandonedTimeout: 10




    #alibaba的druid数据库连接池配置

    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://localhost:3306/parking?useUnicode=true&characterEncoding=utf8   #生产读写分离
      username: root
      password: 123456
      # 使用druid数据源
      filters: stat,wall,log4j #监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      maxActive: 200
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      removeAbandoned: true
      removeAbandonedTimeout: 10
  cache:
    cache-names: cache1
    redis:
      time-to-live: 25s
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379







mybatis:
  mapper-locations: classpath:mapping/*.xml




#log4j 配置
logging:
  level:
    com:
      example: DEBUG






