server:
  port: 9999
#alibaba的druid数据库连接池配置
spring:
  mvc:
    static-path-pattern:/**
  resources:
    static-locations:classpath:/static/
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
          master:
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/fsb?useUnicode=true&useSSL=false&characterEncoding=utf8
          DB2:
            username: root
            password: 123456
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/oil?useUnicode=true&characterEncoding=utf8
         # slave_2:
         #   username: root
         #   password: 123456
          #  driver-class-name: com.mysql.cj.jdbc.Driver
          #  url: jdbc:mysql://xx.xx.xx.xx:3308/dynamic

  cache:
    cache-names: cache1

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    #链接超时时间 毫秒
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000



mybatis-plus:
  mapper-locations:  classpath:mapping/*/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      #id类型
     id-type: auto













